CREATE GENERATOR GEN_USUARIOS_ID;
SET GENERATOR GEN_USUARIOS_ID TO 0;

CREATE TRIGGER TRIG_USUARIOS_AUTOINC FOR usuarios
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    if (NEW.ID_USUARIO is NULL) then NEW.ID_USUARIO = GEN_ID(GEN_USUARIOS_ID, 1);
END
